  MODULE('TESTINVDEV002.CLW')
SelectProduct          PROCEDURE                      !Select a Product Record
UpdateInvoiceDetail    PROCEDURE                      !Form InvoiceDetail
SelectCustomer         PROCEDURE                      !Select a Customer Record
UpdateInvoice          PROCEDURE                      !Form Invoice
SelectCustomerCompany  PROCEDURE                      !Select a CustomerCompany Record
UpdateCustomer         PROCEDURE                      !Form Customer
UpdateConfiguration    PROCEDURE                      !Form Configuration
SelectInvoice          PROCEDURE                      !Select a Invoice Record
UpdateCustomerCompany  PROCEDURE                      !Form CustomerCompany
UpdateProduct          PROCEDURE                      !Form Product
  END
