  MODULE('TESTINVDEV001.CLW')
BrowseCustomerCompany  PROCEDURE                      !Browse the CustomerCompany file
BrowseProduct          PROCEDURE                      !Browse the Product file
BrowseInvoiceDetail    PROCEDURE                      !Browse the InvoiceDetail file
BrowseInvoice          PROCEDURE                      !Browse the Invoice file
BrowseCustomer         PROCEDURE                      !Browse the Customer file
BrowseConfiguration    PROCEDURE                      !Browse the Configuration file
  END
